# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: hallirahul777@gmail.com
author_name: RahulScripts
contract_name: task
deployment_language: python
preset_name: starter
project_name: Task-1-BuildingFoundation

