# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: ypmahajan27@gmail.com
author_name: YashM2704
contract_name: tokens
deployment_language: python
preset_name: starter
project_name: Tokenisation

